pipelines:
  default:
    - step:
        name: Build and test
        image: alpine:3.7
        script:
          - apk add build-base
          - make check
        artifacts:
          - cc1541
    - step:
        name: Build Windows
        image: purplekarrot/mingw-w64-i686
        trigger: manual
        script:
          - make cc1541 test_cc1541 CC=i686-w64-mingw32-gcc
          - mv cc1541 cc1541.exe
          - mv test_cc1541 test_cc1541.exe
          - wine ./test_cc1541.exe ./cc1541.exe
        artifacts:
          - cc1541.exe
    - step:
        name: Build MacOS
        image: andrewd/osxcross
        script:
          - make CC=o64-clang
          - mv cc1541 cc1541_mac
          - mv test_cc1541 test_cc1541_mac
        artifacts:
          - cc1541_mac
          - test_cc1541_mac