pipelines:
  default:
    - step:
        name: Build and test
        image: alpine:3.7
        script:
          - apk add build-base
          - make
          - cd test_cc1541
          - make test
        artifacts:
          - cc1541
    - step:
        name: Build Windows
        image: purplekarrot/mingw-w64-i686
        trigger: manual
        script:
          - make CC=i686-w64-mingw32-gcc
          - mv cc1541 cc1541.exe
          - cd test_cc1541
          - make CC=i686-w64-mingw32-gcc
          - mv test_cc1541 test_cc1541.exe
          - wine test_cc1541.exe ../cc1541.exe
        artifacts:
          - cc1541.exe
