# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: gcc:6.1
image: alpine:3.7

pipelines:
  default:
    - step:
        name: Build and test
        script: # Modify the commands below to build your repository.
          - apk add build-base
          - make
          - cd test_cc1541
          - make test
        artifacts:
          - cc1541
          
