image: alpine:3.7

pipelines:
  default:
    - step:
        name: Build and test
        script:
          - apk add build-base
          - make
          - cd test_cc1541
          - make test
        artifacts:
          - cc1541
    - step:
        name: Build Windows
        trigger: manual
        script:
          - apk add mingw-w64
          - make CC=i686-w64-mingw32-gcc
          - mv cc1541 cc1541.exe
        artifacts:
          - cc1541.exe
